# Repo: MySpace/UserRepo
# File: azure-pipeline2.yml

name: cicd_ci

trigger:
  branches:
    include:
      - master

stages:
- stage: CI_Checks
  jobs:
  - template: rakeshbme1122.TemplateRepo/ci_template.yml
